# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "json", "~> 2.5"

gem "tty-prompt"


gem "colorize", "~> 0.8.1"
